/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ClientesDao;
import DAO.ProcedimientosDao;
import DataTable.JDataTable;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zeus
 */
public class DlGprincipal extends javax.swing.JDialog {
    javax.swing.JFrame  Fabuelo;
    modelo.clientes client = null;
    modelo.procedimientos proced = null;
    /**
     * Creates new form DlGprincipal
     */
    public DlGprincipal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Creates new form principal
     */
    public DlGprincipal() throws ClassNotFoundException, Exception {
        //super(parent, modal);
        initComponents();
        this.JTPROCEDIMIENTOS.setModel(new DefaultTableModel());
        this.cargarBDClientes();


    }

        public DlGprincipal(javax.swing.JFrame  parent, boolean modal) throws ClassNotFoundException, Exception {
        super(parent, modal);
        initComponents();
        this.Fabuelo = parent;
        this.JTPROCEDIMIENTOS.setModel(new DefaultTableModel());
        this.cargarBDClientes();


    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        JBtnModiProcedimiento = new javax.swing.JButton();
        BtnVer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BtnVerAll = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TxtBuscar = new javax.swing.JTextField();
        JbtAddCliente = new javax.swing.JButton();
        JbtEliminar = new javax.swing.JButton();
        JbtAddPro = new javax.swing.JButton();
        JbtnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JBtnEliminarProcedimiento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTCLIENTES = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTPROCEDIMIENTOS = new javax.swing.JTable();

        jToggleButton1.setText("jToggleButton1");

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        JBtnModiProcedimiento.setText("Modificar");
        JBtnModiProcedimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnModiProcedimientoActionPerformed(evt);
            }
        });

        BtnVer.setText("Modificar");
        BtnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CLIENTES");

        BtnVerAll.setText("Todos");
        BtnVerAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerAllActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PROCEDIMIENTOS");

        JbtAddCliente.setText("Añadir");
        JbtAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtAddClienteActionPerformed(evt);
            }
        });

        JbtEliminar.setText("Eliminar");
        JbtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtEliminarActionPerformed(evt);
            }
        });

        JbtAddPro.setText("Añadir ");
        JbtAddPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtAddProActionPerformed(evt);
            }
        });

        JbtnBuscar.setText("Buscar");
        JbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Busquedas Nombre o Dni:");

        JBtnEliminarProcedimiento.setText("Eliminar");
        JBtnEliminarProcedimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnEliminarProcedimientoActionPerformed(evt);
            }
        });

        JTCLIENTES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTCLIENTES.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                JTCLIENTESAncestorMoved(evt);
            }
        });
        JTCLIENTES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JTCLIENTESMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTCLIENTESMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JTCLIENTESMouseEntered(evt);
            }
        });
        JTCLIENTES.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                JTCLIENTESCaretPositionChanged(evt);
            }
        });
        jScrollPane1.setViewportView(JTCLIENTES);

        JTPROCEDIMIENTOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTPROCEDIMIENTOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTPROCEDIMIENTOSMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTPROCEDIMIENTOS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBtnEliminarProcedimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBtnModiProcedimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JbtAddPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(JbtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnVerAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JbtAddCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JbtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtnBuscar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnVerAll)
                        .addGap(33, 33, 33)
                        .addComponent(JbtAddCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnVer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JbtEliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(JbtAddPro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtnModiProcedimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtnEliminarProcedimiento)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnModiProcedimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnModiProcedimientoActionPerformed
        // TODO add your handling code here:
        if (this.JTCLIENTES.getSelectedRow() > -1) {
            if (this.JTPROCEDIMIENTOS.getSelectedRow() > -1) {
                GUI.Procedimientos.ProcedimientosMod pro = new GUI.Procedimientos.ProcedimientosMod(null,this, true, this.client, this.proced);
                pro.setVisible(true);
                this.cargarProcedimientos();

            }
        }
    }//GEN-LAST:event_JBtnModiProcedimientoActionPerformed

    private void BtnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerActionPerformed
        // TODO add your handling code here:
        if (this.JTCLIENTES.getSelectedRow() > -1) {
            String id = (String) this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 0);
            String cliente = (String) this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 1);
            String numcarpe = (String) this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 2);
            String dni = (String) this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 3);
            String dir = (String) this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 4);
            String telf = (String) this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 5);
            String movil = (String) this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 6);
            String info = (String) this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 7);

            modelo.clientes c = new modelo.clientes(Integer.valueOf(id), cliente, numcarpe, dni, dir, telf, movil, info);

            GUI.Clientes.ClientesMod cli = new GUI.Clientes.ClientesMod(null,this, true, c);
            cli.setVisible(true);
            try {
                this.cargarBDClientes();
            } catch (Exception ex) {
                Logger.getLogger(oldprincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_BtnVerActionPerformed

    private void BtnVerAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerAllActionPerformed
        // TODO add your handling code here:

        GUI.Clientes.ClientesAll cli = new GUI.Clientes.ClientesAll(null,this, true);
        cli.setVisible(true);
    }//GEN-LAST:event_BtnVerAllActionPerformed

    private void JbtAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtAddClienteActionPerformed
        // TODO add your handling code here:
        GUI.Clientes.ClientesAdd cli = new GUI.Clientes.ClientesAdd(null,this, true);
        cli.setVisible(true);
        try {
            this.cargarBDClientes();
        } catch (Exception ex) {
            Logger.getLogger(oldprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JbtAddClienteActionPerformed

    private void JbtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtEliminarActionPerformed
        try {
            // TODO add your handling code here:
            if (this.JTCLIENTES.getSelectedRow() > -1){
              int confirmado  =JOptionPane.showConfirmDialog(this.JbtEliminar,"¿Realmente desea eliminar al cliente " +this.client.getcliente() + "?","Atención",JOptionPane.YES_NO_OPTION);

                if (JOptionPane.OK_OPTION == confirmado){  
                
                if(ClientesDao.delete(this.client)>0){
                    this.cargarBDClientes();
                }else{
                    JOptionPane.showMessageDialog(null, "No se puede eliminar el cliente\n contiene procedimientos asociados.");
                    //  System.out.println("No es posible eliminar al cliente.")   ;
                }
            }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(oldprincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(oldprincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(oldprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JbtEliminarActionPerformed

    private void JbtAddProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtAddProActionPerformed
        // TODO add your handling code here:
        if (this.JTCLIENTES.getSelectedRow() > -1) {
            asignarCliente();
            GUI.Procedimientos.ProcedimientosAdd pro = new GUI.Procedimientos.ProcedimientosAdd(this, true,this.client);
            pro.setVisible(true);
            this.cargarProcedimientos();

        }
    }//GEN-LAST:event_JbtAddProActionPerformed

    private void JbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuscarActionPerformed
        try {
            // TODO add your handling code here:
            this.JTCLIENTES.setModel(ClientesDao.buscarBD(this.TxtBuscar.getText()).getDefaultTableModel());
            this.JTPROCEDIMIENTOS.setModel(new DefaultTableModel());
            modelo.util.ocultarColumnas(this.JTCLIENTES, new String[]{"idcliente", "telefono", "info","dc"});
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se ha establecido la conexión\nverifique la configuración o el estado del servidor");
            //Logger.getLogger(oldprincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JbtnBuscarActionPerformed

    private void JBtnEliminarProcedimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnEliminarProcedimientoActionPerformed
        // TODO add your handling code here:
        if (this.JTPROCEDIMIENTOS.getRowCount() > 0) {
            if (this.JTPROCEDIMIENTOS.getSelectedRow() > -1) {

                 int confirmado  =JOptionPane.showConfirmDialog(this.JbtEliminar,"¿Realmente desea eliminar al cliente " +this.proced.getprocedimiento() + "?","Atención",JOptionPane.YES_NO_OPTION);

                if (JOptionPane.OK_OPTION == confirmado){  
                
                try {
                     ProcedimientosDao.delete(this.proced);
                    this.cargarProcedimientos();
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "No se puede eliminar el procedimiento\n, intentelo mas tarde");
                    Logger.getLogger(oldprincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "No se ha establecido la conexión\nverifique la configuración o el estado del servidor");
                    Logger.getLogger(oldprincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
               }
            }
        }

    }//GEN-LAST:event_JBtnEliminarProcedimientoActionPerformed

    private void JTCLIENTESAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JTCLIENTESAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_JTCLIENTESAncestorMoved

    private void JTCLIENTESMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTCLIENTESMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_JTCLIENTESMouseReleased

    private void JTCLIENTESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTCLIENTESMouseClicked
        // TODO add your handling code here:
        this.cargarProcedimientos();
        //

    }//GEN-LAST:event_JTCLIENTESMouseClicked

    private void JTCLIENTESMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTCLIENTESMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_JTCLIENTESMouseEntered

    private void JTCLIENTESCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_JTCLIENTESCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_JTCLIENTESCaretPositionChanged

    private void JTPROCEDIMIENTOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTPROCEDIMIENTOSMouseClicked
        // TODO add your handling code here:
        this.asignarProcedimiento();

    }//GEN-LAST:event_JTPROCEDIMIENTOSMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.salir();
    }//GEN-LAST:event_formWindowClosing

        private void asignarCliente() {
//          if (this.JTCLIENTES.getSelectedRow() > -1) {
        String id = (String) this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 0);
        String cliente = (String) this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 1);
        String numcarpe = (String) this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 2);
        String dni = (String) this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 3);
        String dir = (String) this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 4);
        String telf = (String) this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 5);
        String movil = (String) this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 6);
        String info = (String) this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 7);

        client = new modelo.clientes(Integer.valueOf(id), cliente, numcarpe, dni, dir, telf, movil, info);

//          }
    }

    private void asignarProcedimiento() {
        String dd = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 0);
        Integer id = Integer.valueOf(dd);
        String localidad = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 1);
        String aa = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 2);
        Integer numjuzgado = Integer.valueOf(aa);
        String procedi = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 3);
        String info = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 4);
        String contrario = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 5);
        String ee = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 6);
        Integer id_cliente = Integer.valueOf(ee);
        String ruta_ficheros = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 7);
        this.proced = new modelo.procedimientos(id, localidad, numjuzgado, procedi, info, contrario, id_cliente, ruta_ficheros);

    }

    private void cargarProcedimientos() {
        this.JTPROCEDIMIENTOS.setModel(new JDataTable("Vacio").getDefaultTableModel());

        if (this.JTCLIENTES.getSelectedRow() > -1) {
            this.asignarCliente();
        //    System.out.println(this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 0));
            String a = this.JTCLIENTES.getModel().getValueAt(this.JTCLIENTES.getSelectedRow(), 0).toString();
            Integer i = Integer.valueOf(a);
            try {

                JDataTable dt = ProcedimientosDao.loadBD(i);
                this.JTPROCEDIMIENTOS.setModel(dt.getDefaultTableModel());
                modelo.util.ocultarColumnas(this.JTPROCEDIMIENTOS, new String[]{"IDPROCEDIMIENTO", "ID_CLIENTE", "RUTA_FICHEROS", "INFO"});

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "No se ha establecido la conexión\nverifique la configuración o el estado del servidor");
                //Logger.getLogger(oldprincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            this.client = null;
        }
    }

    private void cargarBDClientes() throws ClassNotFoundException, Exception {

        this.JTCLIENTES.setModel(ClientesDao.loadBD().getDefaultTableModel());
        modelo.util.ocultarColumnas(this.JTCLIENTES, new String[]{"idcliente", "telefono", "info","dc"});

    }

//    private void ocultarColumnas(JTable Jt, String columnName[]) {
//        for (int i = 0; i < Jt.getColumnCount(); i++) {
//
//            if (existe(Jt.getColumnName(i), columnName)) {
//
//                Jt.getColumn(Jt.getColumnName(i)).setMinWidth(0);
//                Jt.getColumn(Jt.getColumnName(i)).setMaxWidth(0);
//
//            }
//
//        }
//
//      //  System.out.println(this.JTCLIENTES.getColumnName(0));
//
//    }
//
//    private boolean existe(String n, String m[]) {
//        for (String a : m) {
//
//            if (a.equalsIgnoreCase(n)) {
//                return true;
//            }
//
//        }
//        return false;
//
//    }
    public void salir(){
        //this.FramePadre.repaint();
        this.Fabuelo.setVisible(true); 
        this.dispose();
    }
            
    
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DlGprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DlGprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DlGprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DlGprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DlGprincipal dialog = new DlGprincipal(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVer;
    private javax.swing.JButton BtnVerAll;
    private javax.swing.JButton JBtnEliminarProcedimiento;
    private javax.swing.JButton JBtnModiProcedimiento;
    private javax.swing.JTable JTCLIENTES;
    private javax.swing.JTable JTPROCEDIMIENTOS;
    private javax.swing.JButton JbtAddCliente;
    private javax.swing.JButton JbtAddPro;
    private javax.swing.JButton JbtEliminar;
    private javax.swing.JButton JbtnBuscar;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
