/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Procedimientos;

import DataTable.JDataTable;
import javax.swing.JOptionPane;

/**
 *
 * @author zeus
 */
public class BscProcedimiento extends javax.swing.JDialog {
    java.awt.Frame Fabuelo;
    modelo.procedimientos pro;
    modelo.clientes cli;
    /**
     * Creates new form BscProcedimiento
     */
    public BscProcedimiento(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        this.Fabuelo= parent;
        initComponents();
        this.JTPROCEDIMIENTOS.setModel((new JDataTable("a")).getDefaultTableModel());
//       this.cargarProcedimientos();
//        this.JTPROCEDIMIENTOS.setModel(modelo.procedimientos.loadBD(-1).getDefaultTableModel());
//        modelo.util.ocultarColumnas(JTPROCEDIMIENTOS, new String[]{"IdProcedimiento","IdCliente","Id_Cliente","Ruta_Ficheros"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTPROCEDIMIENTOS = new javax.swing.JTable();
        JBtnBuscar = new javax.swing.JButton();
        JBtnVer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Procedimiento:");

        JTPROCEDIMIENTOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTPROCEDIMIENTOS);

        JBtnBuscar.setText("Buscar");
        JBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnBuscarActionPerformed(evt);
            }
        });

        JBtnVer.setText("Ver");
        JBtnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                        .addComponent(JBtnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnBuscar)
                    .addComponent(JBtnVer))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnBuscarActionPerformed
        try {
            // TODO add your handling code here:
            this.cargarProcedimientos();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se ha podido realizar la consulta a la base de datos\n revise configuración y estado del servidor");
            //Logger.getLogger(BscProcedimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_JBtnBuscarActionPerformed
 public void cargarProcedimientos() throws Exception{
                this.JTPROCEDIMIENTOS.setModel(DAO.ProcedimientosDao.loadBD(this.TxtBusqueda.getText()).getDefaultTableModel() );
                 modelo.util.ocultarColumnas(JTPROCEDIMIENTOS, new String[]{"IdProcedimiento","IdCliente","Id_Cliente","Ruta_Ficheros"});
 } 
    private void JBtnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnVerActionPerformed
        // TODO add your handling code here:
        if(this.JTPROCEDIMIENTOS.getSelectedRow()>-1){
            try {
                //IDPROCEDIMIENTO,LOCALIDAD,NUMJUZGADO,PROCEDIMIENTO,PROCEDIMIENTOS.INFO,CONTRARIO,IDCLIENTE,RUTA_FICHEROS,CLIENTE
                String dd = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 0);
                Integer id = Integer.valueOf(dd);
                String localidad = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 1);
                String aa = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 2);
                Integer numjuzgado = Integer.valueOf(aa);
                String procedi = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 3);
                String info = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 4);
                String contrario = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 5);
                String ee = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 6);
                Integer id_cliente = Integer.valueOf(ee);
                String ruta_ficheros = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 7);
                String cliente = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 8);
                String dni = (String) this.JTPROCEDIMIENTOS.getModel().getValueAt(this.JTPROCEDIMIENTOS.getSelectedRow(), 9);
                this.cli= new modelo.clientes(id_cliente ,cliente,dni);
                this.pro= new modelo.procedimientos(id, localidad, numjuzgado, procedi, info, contrario, id_cliente, ruta_ficheros);
                this.setVisible(false);
                GUI.Procedimientos.ProcedimientosMod f= new GUI.Procedimientos.ProcedimientosMod(this.Fabuelo,this,true,this.cli,this.pro);
                f.setVisible(true);
                this.cargarProcedimientos();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "No se han podido obtener los datos.");
                //Logger.getLogger(BscProcedimiento.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        }
        
        
    }//GEN-LAST:event_JBtnVerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.Fabuelo.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BscProcedimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BscProcedimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BscProcedimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BscProcedimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                BscProcedimiento dialog = new BscProcedimiento(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnBuscar;
    private javax.swing.JButton JBtnVer;
    private javax.swing.JTable JTPROCEDIMIENTOS;
    private javax.swing.JTextField TxtBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
