/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Procedimientos;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author zeus
 */
public class ProcedimientosAdd extends javax.swing.JDialog {
    modelo.clientes cliente =null;
    modelo.procedimientos proc=null;
    javax.swing.JDialog padre;
    /**
     * Creates new form Procedimientos
     * @param parent
     * @param modal
     */
    public ProcedimientosAdd(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

     public ProcedimientosAdd(java.awt.Frame parent, boolean modal,modelo.clientes cli) {
        super(parent, modal);
        initComponents();
        this.cliente=cli;
        this.TxtCliente.setText(cli.getdni() +" " +cli.getcliente());
//        this.TxtContrario.setText(max.getUtil.getNombreCompleto());
//        this.TxtInfo.setText(max.getUtil.getCausaDetalle());
//        this.TxtLocalidad.setText(max.getUtil.getLocalidad());
//        this.TxtFicheros.setText(max.getUtil.getVerbo());
//        this.TxtProcedimiento.setText(max.getUtil.getExpediente());
        this.CBLocalidades.addItem("Sin Localidad");
        for(int i =0;i<max.array.localidades.length;i++){
            this.CBLocalidades.addItem(max.array.localidades[i]);
        }
              
        
       
    }
    
      public ProcedimientosAdd(javax.swing.JDialog parent, boolean modal,modelo.clientes cli) {
        super(parent, modal);
        initComponents();
        this.padre=parent;
        this.cliente=cli;
        this.TxtCliente.setText(cli.getdni() +" " +cli.getcliente());
//        this.TxtContrario.setText(max.getUtil.getNombreCompleto());
//        this.TxtInfo.setText(max.getUtil.getCausaDetalle());
//        this.TxtLocalidad.setText(max.getUtil.getLocalidad());
//        this.TxtFicheros.setText(max.getUtil.getVerbo());
//        this.TxtProcedimiento.setText(max.getUtil.getExpediente());
        this.CBLocalidades.addItem("Sin Localidad");
        for(int i =0;i<max.array.localidades.length;i++){
            this.CBLocalidades.addItem(max.array.localidades[i]);
        }
              
        
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtIdProcedimiento = new javax.swing.JTextField();
        TxtLocalidad = new javax.swing.JTextField();
        TxtProcedimiento = new javax.swing.JTextField();
        TxtContrario = new javax.swing.JTextField();
        TxtFicheros = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtInfo = new javax.swing.JTextArea();
        JbtSalir = new javax.swing.JButton();
        JbtGuardar = new javax.swing.JButton();
        TxtCliente = new javax.swing.JTextField();
        CBNumJuzgado = new javax.swing.JComboBox();
        CBLocalidades = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("ID:");

        jLabel2.setText("Localidad:");

        jLabel3.setText("Juzgado:");

        jLabel4.setText("Procedimiento:");

        jLabel5.setText("Información:");

        jLabel6.setText("Contrario:");

        jLabel7.setText("Ficheros:");

        TxtIdProcedimiento.setEditable(false);

        TxtLocalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtLocalidadKeyTyped(evt);
            }
        });

        TxtProcedimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtProcedimientoKeyTyped(evt);
            }
        });

        TxtContrario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtContrarioKeyTyped(evt);
            }
        });

        TxtFicheros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtFicherosKeyTyped(evt);
            }
        });

        TxtInfo.setColumns(20);
        TxtInfo.setRows(5);
        jScrollPane1.setViewportView(TxtInfo);

        JbtSalir.setText("Salir");
        JbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtSalirActionPerformed(evt);
            }
        });

        JbtGuardar.setText("Guardar");
        JbtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtGuardarActionPerformed(evt);
            }
        });

        TxtCliente.setEditable(false);

        CBNumJuzgado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        CBLocalidades.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBLocalidadesItemStateChanged(evt);
            }
        });

        jButton1.setText("Autocompletar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(48, 48, 48)
                                .addComponent(TxtLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JbtGuardar)
                                        .addGap(18, 18, 18)
                                        .addComponent(JbtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(18, 18, 18)
                                            .addComponent(TxtIdProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(49, 49, 49)
                                            .addComponent(TxtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TxtFicheros, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CBNumJuzgado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtContrario, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtIdProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CBNumJuzgado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(TxtProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtContrario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFicheros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtGuardar)
                    .addComponent(JbtSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JbtSalirActionPerformed

    private void JbtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtGuardarActionPerformed
  
            // TODO add your handling code here:
            //public procedimientos(Integer idprocedimiento,String localidad,Integer numjuzgado,String procedimiento,String info,String contrario,Integer id_cliente,String ruta_ficheros){
        try {  
            proc= new modelo.procedimientos(0,this.TxtLocalidad.getText(),this.CBNumJuzgado.getSelectedIndex(),this.TxtProcedimiento.getText(),this.TxtInfo.getText(),this.TxtContrario.getText(), this.cliente.getidcliente(), this.TxtFicheros.getText());
            DAO.ProcedimientosDao.add(proc);
            this.dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Se ha producido un error en la conexión\n revise la configuración o el estado del servidor");
            //Logger.getLogger(ProcedimientosAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_JbtGuardarActionPerformed

    private void CBLocalidadesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBLocalidadesItemStateChanged
        // TODO add your handling code here:
        this.TxtLocalidad.setText(this.CBLocalidades.getSelectedItem().toString());
    }//GEN-LAST:event_CBLocalidadesItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
//        this.TxtContrario.setText(max.getUtil.getNombreCompleto());
//        this.TxtFicheros.setText(max.getUtil.getMatriculas());
//        this.TxtInfo.setText(max.getUtil.getCausaDetalle());
//        this.TxtLocalidad.setText(max.getUtil.getLocalidad());
//        this.TxtProcedimiento.setText(max.getUtil.getExpediente());
//        this.CBNumJuzgado.setSelectedIndex(3);
//        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TxtLocalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtLocalidadKeyTyped
        // TODO add your handling code here:
         if(this.TxtLocalidad.getText().length()>19){
           evt.consume();
       }
    }//GEN-LAST:event_TxtLocalidadKeyTyped

    private void TxtProcedimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtProcedimientoKeyTyped
        // TODO add your handling code here:
         if(this.TxtProcedimiento.getText().length()>19){
           evt.consume();
       }
    }//GEN-LAST:event_TxtProcedimientoKeyTyped

    private void TxtContrarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtContrarioKeyTyped
        // TODO add your handling code here:
         if(this.TxtContrario.getText().length()>99){
           evt.consume();
       }
    }//GEN-LAST:event_TxtContrarioKeyTyped

    private void TxtFicherosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtFicherosKeyTyped
        // TODO add your handling code here:
         if(this.TxtFicheros.getText().length()>19){
           evt.consume();
       }
    }//GEN-LAST:event_TxtFicherosKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ProcedimientosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ProcedimientosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ProcedimientosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ProcedimientosAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ProcedimientosAdd dialog = new ProcedimientosAdd(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CBLocalidades;
    private javax.swing.JComboBox CBNumJuzgado;
    private javax.swing.JButton JbtGuardar;
    private javax.swing.JButton JbtSalir;
    private javax.swing.JTextField TxtCliente;
    private javax.swing.JTextField TxtContrario;
    private javax.swing.JTextField TxtFicheros;
    private javax.swing.JTextField TxtIdProcedimiento;
    private javax.swing.JTextArea TxtInfo;
    private javax.swing.JTextField TxtLocalidad;
    private javax.swing.JTextField TxtProcedimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
