/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Procedimientos;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author zeus
 */
public class ProcedimientosMod extends javax.swing.JDialog {
    modelo.clientes cliente =null;
    modelo.procedimientos proc=null;
    java.awt.Frame Fabuelo;
    javax.swing.JDialog Dpadre;
    /**
     * Creates new form Procedimientos
     */
//    public ProcedimientosMod(java.awt.Frame parent, javax.swing.JDialog Dpadre, boolean modal) {
//        super(parent, modal);
//        initComponents();
//        this.Dpadre=Dpadre;
//        this.Fabuelo= parent;
//    }

//     public ProcedimientosMod(java.awt.Frame parent, boolean modal,modelo.clientes cli,modelo.procedimientos pro) {
//        super(parent, modal);
//        initComponents();
//        this.Fabuelo=parent;
//        this.Dpadre= null;
//        this.cliente=cli;
//        this.proc=pro;
//        this.TxtCliente.setText(cli.getdni() +" " +cli.getcliente());
//        this.TxtLocalidad.setText(pro.getlocalidad());
//        this.TxtProcedimiento.setText(pro.getprocedimiento());
//        this.TxtInfo.setText(pro.getinfo());
//        this.TxtFicheros.setText(pro.getruta_ficheros());
//        this.TxtContrario.setText(pro.getcontrario());
//        this.TxtIdProcedimiento.setText(String.valueOf(pro.getidprocedimiento()));
//        this.CBNumJuzgado.setSelectedIndex(pro.getnumjuzgado());
//       
//    }
      public ProcedimientosMod(java.awt.Frame parent,javax.swing.JDialog padre, boolean modal,modelo.clientes cli,modelo.procedimientos pro) {
        super(parent, modal);
        initComponents();
        this.Fabuelo = parent;
        this.Dpadre = padre;
        
        this.cliente=cli;
        this.proc=pro;
        this.TxtCliente.setText(cli.getdni() +" " +cli.getcliente());
        this.TxtLocalidad.setText(pro.getlocalidad());
        this.TxtProcedimiento.setText(pro.getprocedimiento());
        this.TxtInfo.setText(pro.getinfo());
        this.TxtFicheros.setText(pro.getruta_ficheros());
        this.TxtContrario.setText(pro.getcontrario());
        this.TxtIdProcedimiento.setText(String.valueOf(pro.getidprocedimiento()));
        this.CBNumJuzgado.setSelectedIndex(pro.getnumjuzgado());
       
    }
    
   
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtIdProcedimiento = new javax.swing.JTextField();
        TxtLocalidad = new javax.swing.JTextField();
        TxtProcedimiento = new javax.swing.JTextField();
        TxtContrario = new javax.swing.JTextField();
        TxtFicheros = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtInfo = new javax.swing.JTextArea();
        JbtSalir = new javax.swing.JButton();
        JbtGuardar = new javax.swing.JButton();
        TxtCliente = new javax.swing.JTextField();
        CBNumJuzgado = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel2.setText("Localidad:");

        jLabel3.setText("Juzgado:");

        jLabel4.setText("Procedimiento:");

        jLabel5.setText("Información:");

        jLabel6.setText("Contrario:");

        jLabel7.setText("Ficheros:");

        TxtIdProcedimiento.setEditable(false);

        TxtLocalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtLocalidadKeyTyped(evt);
            }
        });

        TxtProcedimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtProcedimientoKeyTyped(evt);
            }
        });

        TxtContrario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtContrarioKeyTyped(evt);
            }
        });

        TxtFicheros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtFicherosKeyTyped(evt);
            }
        });

        TxtInfo.setColumns(20);
        TxtInfo.setRows(5);
        jScrollPane1.setViewportView(TxtInfo);

        JbtSalir.setText("Salir");
        JbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtSalirActionPerformed(evt);
            }
        });

        JbtGuardar.setText("Guardar");
        JbtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtGuardarActionPerformed(evt);
            }
        });

        TxtCliente.setEditable(false);

        CBNumJuzgado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JbtGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JbtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(TxtProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtFicheros))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(TxtIdProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TxtCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TxtLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(CBNumJuzgado, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TxtContrario)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtIdProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtFicheros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtContrario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(CBNumJuzgado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtGuardar)
                    .addComponent(JbtSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtSalirActionPerformed
        // TODO add your handling code here:
      this.salir();
    }//GEN-LAST:event_JbtSalirActionPerformed

    private void JbtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtGuardarActionPerformed
  
            // TODO add your handling code here:
            //public procedimientos(Integer idprocedimiento,String localidad,Integer numjuzgado,String procedimiento,String info,String contrario,Integer id_cliente,String ruta_ficheros){
        try {  
            proc= new modelo.procedimientos(proc.getidprocedimiento(),this.TxtLocalidad.getText(),this.CBNumJuzgado.getSelectedIndex(),this.TxtProcedimiento.getText(),this.TxtInfo.getText(),this.TxtContrario.getText(), this.cliente.getidcliente(), this.TxtFicheros.getText());
            DAO.ProcedimientosDao.update(proc);
            this.salir();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "No se ha podido conectar a la BD por un error de clases");
            //Logger.getLogger(ProcedimientosMod.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No ha sido posible guardar los datos\n la consulta o la base de datos no es correcta");
            //Logger.getLogger(ProcedimientosMod.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_JbtGuardarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
       this.salir();
    }//GEN-LAST:event_formWindowClosing

    private void TxtLocalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtLocalidadKeyTyped
        // TODO add your handling code here:
         if(this.TxtLocalidad.getText().length()>19){
           evt.consume();
       }
    }//GEN-LAST:event_TxtLocalidadKeyTyped

    private void TxtProcedimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtProcedimientoKeyTyped
        // TODO add your handling code here:
         if(this.TxtProcedimiento.getText().length()>19){
           evt.consume();
       }
    }//GEN-LAST:event_TxtProcedimientoKeyTyped

    private void TxtContrarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtContrarioKeyTyped
        // TODO add your handling code here:
         if(this.TxtContrario.getText().length()>99){
           evt.consume();
       }
    }//GEN-LAST:event_TxtContrarioKeyTyped

    private void TxtFicherosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtFicherosKeyTyped
        // TODO add your handling code here:
         if(this.TxtFicheros.getText().length()>19){
           evt.consume();
       }
    }//GEN-LAST:event_TxtFicherosKeyTyped

    public void salir(){
        this.setVisible(false);
      if(this.Dpadre!=null){
         this.Dpadre.setVisible(true);
         
      }
         
      this.dispose();
    }
    
   
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ProcedimientosMod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ProcedimientosMod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ProcedimientosMod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ProcedimientosMod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ProcedimientosMod dialog = new ProcedimientosMod(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CBNumJuzgado;
    private javax.swing.JButton JbtGuardar;
    private javax.swing.JButton JbtSalir;
    private javax.swing.JTextField TxtCliente;
    private javax.swing.JTextField TxtContrario;
    private javax.swing.JTextField TxtFicheros;
    private javax.swing.JTextField TxtIdProcedimiento;
    private javax.swing.JTextArea TxtInfo;
    private javax.swing.JTextField TxtLocalidad;
    private javax.swing.JTextField TxtProcedimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
