/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Clientes;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author zeus
 */
public class ClientesAdd extends javax.swing.JDialog {

    private java.awt.Frame Fabuelo;
    private javax.swing.JDialog Dpadre;
    private modelo.clientes cliente = null;
    //private boolean update = false;

    /**
     * Creates new form Clientes
     * @param parent
     * @param padre
     * @param modal
     */
    public ClientesAdd(java.awt.Frame parent, javax.swing.JDialog padre, boolean modal) {
        super(parent, modal);
        initComponents();
        this.Fabuelo = parent;
        this.Dpadre = padre;
        this.cliente = new modelo.clientes();
        this.cliente.setidcliente(0);
        //  update = false;
    }

//    public ClientesAdd(java.awt.Frame parent , javax.swing.JDialog padre, boolean modal) {
//        super(parent, modal);
//        initComponents();
//        this.padre = parent;
//        this.madre = madre;
//        this.cliente = new modelo.clientes();
//        this.cliente.setidcliente(0);
//        update = false;
//    }
    /**
     * Creates new form Clientes
     */
//    public ClientesAdd(java.awt.Frame parent, javax.swing.JDialog padre, boolean modal, modelo.clientes cliente) {
//        super(parent, modal);
//        initComponents();
//        this.Fabuelo = parent;
//        this.Dpadre = padre;
//        this.cliente = cliente;
//        this.TxtIDCliente.setText(this.cliente.getidcliente().toString());
//        this.TxtDNI.setText(this.cliente.getdni());
//        this.TxtNombre.setText(this.cliente.getcliente());
//        this.TxtCarpeta.setText(this.cliente.getnumcarpeta());
//        this.TxtDireccion.setText(this.cliente.getdireccion());
//        this.TxtInfo.setText(this.cliente.getinfo());
//        this.TxtTelf.setText(this.cliente.gettelefono());
//        this.TxtMovil.setText(this.cliente.getmovil());
//        // this..setText(this.cliente.getdni());
//        // update = true;
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtDNI = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtDireccion = new javax.swing.JTextField();
        TxtTelf = new javax.swing.JTextField();
        TxtMovil = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtInfo = new javax.swing.JTextArea();
        BtnSalir = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        TxtIDCliente = new javax.swing.JTextField();
        TxtCarpeta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("DNI:");

        jLabel3.setText("NOMBRE:");

        jLabel4.setText("DIRECCION:");

        jLabel5.setText("TELF:");

        jLabel6.setText("MOVIl:");

        TxtDNI.setColumns(12);
        TxtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDNIKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtDNIKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtDNIKeyReleased(evt);
            }
        });

        TxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNombreKeyTyped(evt);
            }
        });

        TxtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDireccionKeyTyped(evt);
            }
        });

        TxtTelf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTelfKeyTyped(evt);
            }
        });

        TxtMovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtMovilKeyTyped(evt);
            }
        });

        TxtInfo.setColumns(20);
        TxtInfo.setRows(5);
        TxtInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtInfoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(TxtInfo);

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        TxtIDCliente.setEditable(false);
        TxtIDCliente.setBackground(new java.awt.Color(253, 128, 2));
        TxtIDCliente.setForeground(new java.awt.Color(42, 35, 18));
        TxtIDCliente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        TxtCarpeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCarpetaKeyTyped(evt);
            }
        });

        jLabel7.setText("Carpeta:");

        jButton1.setText("Autocompletar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TxtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(TxtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TxtCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TxtIDCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(TxtTelf, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGap(26, 26, 26)
                                        .addComponent(TxtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159)
                        .addComponent(BtnGuardar)
                        .addGap(115, 115, 115)
                        .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(BtnGuardar)
                    .addComponent(BtnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
       
        try {
            cliente.setcliente(this.TxtNombre.getText());
            cliente.setnumcarpeta(this.TxtCarpeta.getText());
            cliente.setdni(this.TxtDNI.getText());
            cliente.setdireccion(this.TxtDireccion.getText());
            cliente.settelefono(this.TxtTelf.getText());
            cliente.setmovil(this.TxtMovil.getText());
            cliente.setinfo(this.TxtInfo.getText());

            if (DAO.ClientesDao.add(cliente) > 0) {
               // this.dispose();
                  this.salir();
            } else {
                javax.swing.JOptionPane.showConfirmDialog(this, "Ha habido un error no se ha podido guardar los datos");
            }
          

        } catch (ClassNotFoundException | SQLException ex) {
              JOptionPane.showMessageDialog(null, "No se puede acceder a la base de datos\n revise configuracion y estado del servidor");
           // Logger.getLogger(ClientesAdd.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        this.salir();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.salir();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

//        this.TxtDNI.setText(max.getUtil.getDNI());
//        this.TxtNombre.setText(max.getUtil.getNombreCompleto());
//        this.TxtCarpeta.setText(max.getUtil.getVerbo());
//        this.TxtDireccion.setText(max.getUtil.getDireccion());
//        this.TxtInfo.setText(max.getUtil.getCita());
//        this.TxtTelf.setText(max.getUtil.getTelefono());
//        this.TxtMovil.setText(max.getUtil.getTelefono());


    }//GEN-LAST:event_jButton1ActionPerformed

    private void TxtDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDNIKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_TxtDNIKeyReleased

    private void TxtDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDNIKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_TxtDNIKeyPressed

    private void TxtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDNIKeyTyped
        // TODO add your handling code here:

        if (this.TxtDNI.getText().length() > 11) {

            evt.consume();

        }
    }//GEN-LAST:event_TxtDNIKeyTyped

    private void TxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreKeyTyped
        // TODO add your handling code here:
        if (this.TxtNombre.getText().length() > 49) {

            evt.consume();

        }
    }//GEN-LAST:event_TxtNombreKeyTyped

    private void TxtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDireccionKeyTyped
        // TODO add your handling code here:
        if (this.TxtDireccion.getText().length() > 149) {

            evt.consume();

        }
    }//GEN-LAST:event_TxtDireccionKeyTyped

    private void TxtTelfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelfKeyTyped
        // TODO add your handling code here:
        if (this.TxtTelf.getText().length() > 11) {

            evt.consume();

        }
    }//GEN-LAST:event_TxtTelfKeyTyped

    private void TxtMovilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMovilKeyTyped
        // TODO add your handling code here:
        if (this.TxtMovil.getText().length() > 11) {

            evt.consume();

        }
    }//GEN-LAST:event_TxtMovilKeyTyped

    private void TxtInfoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtInfoKeyTyped
        // TODO add your handling code here:
        if (this.TxtInfo.getText().length() > 499) {

            evt.consume();

        }

    }//GEN-LAST:event_TxtInfoKeyTyped

    private void TxtCarpetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCarpetaKeyTyped
        // TODO add your handling code here:

        if (this.TxtCarpeta.getText().length() > 11) {

            evt.consume();

        }
    }//GEN-LAST:event_TxtCarpetaKeyTyped

    private void salir() {

        if (this.Dpadre != null) {
            System.out.println("mostrando padre");
            this.setVisible(false);
            if(this.Dpadre.getClass().getSimpleName().equalsIgnoreCase(GUI.Clientes.BscCliente.class.getSimpleName())){
                ((GUI.Clientes.BscCliente) this.Dpadre).cargarBDClientes();
            }
//            else if((this.Dpadre.getClass().getSimpleName().equalsIgnoreCase(GUI.principal.class.getSimpleName()))){
//                ((GUI.DlGprincipal) this.Dpadre);
//            }
            this.Dpadre.setVisible(true);
            this.dispose();
            
        }
       this.dispose();

    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Clientes dialog = new Clientes(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JTextField TxtCarpeta;
    private javax.swing.JTextField TxtDNI;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtIDCliente;
    private javax.swing.JTextArea TxtInfo;
    private javax.swing.JTextField TxtMovil;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtTelf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
