/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Clientes;

import DataTable.JDataTable;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author zeus
 */
public class ClientesAll extends javax.swing.JDialog {
    private JDataTable dtClientes=null;
    private modelo.clientes cliente= new modelo.clientes();
    private Integer linea =-1;
    /**
     * Creates new form Clientes
     */
    public ClientesAll(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            this.cargarBD();

        } catch (Exception ex) {
            Logger.getLogger(ClientesAll.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

     public ClientesAll(java.awt.Frame parent,javax.swing.JDialog pa, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            this.cargarBD();

        } catch (Exception ex) {
            Logger.getLogger(ClientesAll.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     /**
     * Creates new form Clientes
     */
//    public ClientesAll(java.awt.Frame parent, boolean modal, modelo.clientes cliente) {
//        super(parent, modal);
//        initComponents();
//        this.cliente=cliente;
//        this.TxtIDCliente.setText(this.cliente.getidcliente().toString());
//        this.TxtDNI.setText(this.cliente.getdni());
//        this.TxtNombre.setText(this.cliente.getcliente());
//        this.TxtDireccion.setText(this.cliente.getdireccion());
//        this.TxtInfo.setText(this.cliente.getinfo());
//        this.TxtTelf.setText(this.cliente.gettelefono());
//        this.TxtMovil.setText(this.cliente.getmovil());
//       // this..setText(this.cliente.getdni());
//        
//        
//        
//    }
//    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtDNI = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtDireccion = new javax.swing.JTextField();
        TxtTelf = new javax.swing.JTextField();
        TxtMovil = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtInfo = new javax.swing.JTextArea();
        BtnSalir = new javax.swing.JButton();
        BtnAceptar = new javax.swing.JButton();
        TxtIDCliente = new javax.swing.JTextField();
        BtnAtras = new javax.swing.JButton();
        BtnSiguiente = new javax.swing.JButton();
        BtnNuevo = new javax.swing.JButton();
        LblTotalClientes = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtNumCarpeta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("ID");

        jLabel2.setText("DNI:");

        jLabel3.setText("NOMBRE:");

        jLabel4.setText("DIRECCION:");

        jLabel5.setText("TELF:");

        jLabel6.setText("MOVIl:");

        TxtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDNIKeyTyped(evt);
            }
        });

        TxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNombreKeyTyped(evt);
            }
        });

        TxtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDireccionKeyTyped(evt);
            }
        });

        TxtTelf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTelfKeyTyped(evt);
            }
        });

        TxtMovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtMovilKeyTyped(evt);
            }
        });

        TxtInfo.setColumns(20);
        TxtInfo.setRows(5);
        TxtInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtInfoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(TxtInfo);

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        BtnAceptar.setText("Aceptar");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        TxtIDCliente.setEditable(false);
        TxtIDCliente.setBackground(new java.awt.Color(253, 128, 2));
        TxtIDCliente.setForeground(new java.awt.Color(42, 35, 18));
        TxtIDCliente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        BtnAtras.setText("Atras");
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });

        BtnSiguiente.setText("Siguiente");
        BtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteActionPerformed(evt);
            }
        });

        BtnNuevo.setText("Nuevo");
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });

        LblTotalClientes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblTotalClientes.setText("Total de Clientes");

        jLabel7.setText("Carpeta:");

        TxtNumCarpeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNumCarpetaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtTelf, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(TxtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TxtDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(TxtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtNumCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(TxtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(80, 80, 80)
                                        .addComponent(LblTotalClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(BtnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnSiguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(TxtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblTotalClientes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TxtNumCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalir)
                    .addComponent(BtnAceptar)
                    .addComponent(BtnNuevo)
                    .addComponent(BtnSiguiente)
                    .addComponent(BtnAtras))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        try {
            // TODO add your handling code here:
            
            cliente.setcliente( this.TxtNombre.getText());
            cliente.setnumcarpeta(this.TxtNumCarpeta.getText());
            cliente.setdni( this.TxtDNI.getText());
            cliente.setdireccion( this.TxtDireccion.getText());
            cliente.settelefono(this.TxtTelf.getText());
            cliente.setmovil(this.TxtMovil.getText());
            cliente.setinfo(this.TxtInfo.getText());
            DAO.ClientesDao.update(cliente);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Se ha producido un error al guardar\n revise la configuración y el estado del servidor");
            //Logger.getLogger(ClientesAll.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Se ha producido un error al guardar\nrevise la consulta o el estado del servidor.");
           // Logger.getLogger(ClientesAll.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void BtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteActionPerformed
        // TODO add your handling code here:
        this.siguiente();
    }//GEN-LAST:event_BtnSiguienteActionPerformed

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        // TODO add your handling code here:
        this.atras();
    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        // TODO add your handling code here:
        if(this.BtnNuevo.getText().equals("Nuevo")){
        this.cliente= new modelo.clientes();
            this.TxtIDCliente.setText("");
            this.TxtDNI.setText("");
            this.TxtNombre.setText("");
            this.TxtNumCarpeta.setText("");
            this.TxtDireccion.setText("");
            this.TxtInfo.setText("");
            this.TxtTelf.setText("");
            this.TxtMovil.setText("");
            this.BtnNuevo.setText("Guardar");
            
        }else{
            cliente.setidcliente(0);
            cliente.setcliente( this.TxtNombre.getText());
            cliente.setnumcarpeta(this.TxtNumCarpeta.getText());
            cliente.setdni( this.TxtDNI.getText());
            cliente.setdireccion( this.TxtDireccion.getText());
            cliente.settelefono(this.TxtTelf.getText());
            cliente.setmovil(this.TxtMovil.getText());
            cliente.setinfo(this.TxtInfo.getText());
            
            try {
                //            this.TxtIDCliente.setText(this.cliente.getidcliente().toString());
//            this.TxtDNI.setText(this.cliente.getdni());
//            this.TxtNombre.setText(this.cliente.getcliente());
//            this.TxtDireccion.setText(this.cliente.getdireccion());
//            this.TxtInfo.setText(this.cliente.getinfo());
//            this.TxtTelf.setText(this.cliente.gettelefono());
//            this.TxtMovil.setText(this.cliente.getmovil());
                
                DAO.ClientesDao.add(cliente);
                this.BtnNuevo.setText("Nuevo");
                this.cargarBD(this.dtClientes.getRowsLenth()-1);
                
                
            } catch (ClassNotFoundException ex ) {
                JOptionPane.showMessageDialog(null, "Se ha producido un error en la clase de acceso a la BD\n revise configuracion y estado del servidor");
                //Logger.getLogger(ClientesAll.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Se ha producido un error en la consulta\n revise la configuracion y el estado del servidor");
                //Logger.getLogger(ClientesAll.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void TxtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDNIKeyTyped
        // TODO add your handling code here:
         if(this.TxtDNI.getText().length()>11){
           evt.consume();
       }
    }//GEN-LAST:event_TxtDNIKeyTyped

    private void TxtNumCarpetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNumCarpetaKeyTyped
        // TODO add your handling code here:
         if(this.TxtNumCarpeta.getText().length()>11){
           evt.consume();
       }
    }//GEN-LAST:event_TxtNumCarpetaKeyTyped

    private void TxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreKeyTyped
        // TODO add your handling code here:
         if(this.TxtNombre.getText().length()>49){
           evt.consume();
       }
    }//GEN-LAST:event_TxtNombreKeyTyped

    private void TxtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDireccionKeyTyped
        // TODO add your handling code here:
         if(this.TxtDireccion.getText().length()>149){
           evt.consume();
       }
    }//GEN-LAST:event_TxtDireccionKeyTyped

    private void TxtTelfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelfKeyTyped
        // TODO add your handling code here:
         if(this.TxtTelf.getText().length()>11){
           evt.consume();
       }
    }//GEN-LAST:event_TxtTelfKeyTyped

    private void TxtMovilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMovilKeyTyped
        // TODO add your handling code here:
         if(this.TxtMovil.getText().length()>11){
           evt.consume();
       }
    }//GEN-LAST:event_TxtMovilKeyTyped

    private void TxtInfoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtInfoKeyTyped
        // TODO add your handling code here:
         if(this.TxtInfo.getText().length()>499){
           evt.consume();
       }
    }//GEN-LAST:event_TxtInfoKeyTyped

    private void siguiente(){
        linea ++;
        if(this.dtClientes.getRowsLenth()>1 && linea < this.dtClientes.getRowsLenth()){
           
            this.enlazarCampos();
//            cliente = new modelo.clientes();
//            cliente.setidcliente( Integer.valueOf(this.dtClientes.getColumn(0).getRow(linea)));
//            cliente.setcliente( this.dtClientes.getColumn(1).getRow(linea));
//            cliente.setnumcarpeta(this.dtClientes.getColumn(2).getRow(linea));
//            cliente.setdni( this.dtClientes.getColumn(3).getRow(linea));
//            cliente.setdireccion( this.dtClientes.getColumn(4).getRow(linea));
//            cliente.settelefono(this.dtClientes.getColumn(5).getRow(linea));
//            cliente.setmovil(this.dtClientes.getColumn(6).getRow(linea));
//            cliente.setinfo(this.dtClientes.getColumn(7).getRow(linea));
//            
//            this.TxtIDCliente.setText(this.cliente.getidcliente().toString());
//            this.TxtDNI.setText(this.cliente.getdni());
//            this.TxtNombre.setText(this.cliente.getcliente());
//            this.TxtNumCarpeta.setText(this.cliente.getnumcarpeta());
//            this.TxtDireccion.setText(this.cliente.getdireccion());
//            this.TxtInfo.setText(this.cliente.getinfo());
//            this.TxtTelf.setText(this.cliente.gettelefono());
//            this.TxtMovil.setText(this.cliente.getmovil());
         
            
            
        }else{
            linea --;
        }
            
        
        
        
    }
            
     private void atras(){
        if(this.dtClientes.getRowsLenth()>0 && linea > 0 ){
            linea --;
           this.enlazarCampos();
        }
        
    }
     private void enlazarCampos(){
         
         
            cliente = new modelo.clientes();
            cliente.setidcliente( Integer.valueOf(this.dtClientes.getColumn(0).getRow(linea)));
            cliente.setcliente( this.dtClientes.getColumn(1).getRow(linea));
            cliente.setnumcarpeta(this.dtClientes.getColumn(2).getRow(linea));
            cliente.setdni( this.dtClientes.getColumn(3).getRow(linea));
            cliente.setdireccion( this.dtClientes.getColumn(4).getRow(linea));
            cliente.settelefono(this.dtClientes.getColumn(5).getRow(linea));
            cliente.setmovil(this.dtClientes.getColumn(6).getRow(linea));
            cliente.setinfo(this.dtClientes.getColumn(7).getRow(linea));
            
            this.TxtIDCliente.setText(this.cliente.getidcliente().toString());
            this.TxtDNI.setText(this.cliente.getdni());
            this.TxtNombre.setText(this.cliente.getcliente());
            this.TxtNumCarpeta.setText(this.cliente.getnumcarpeta());
            this.TxtDireccion.setText(this.cliente.getdireccion());
            this.TxtInfo.setText(this.cliente.getinfo());
            this.TxtTelf.setText(this.cliente.gettelefono());
            this.TxtMovil.setText(this.cliente.getmovil());
         
         
         
     }
     
     
     
            
    private void cargarBD(){
        
        try {
            linea=-1;
            dtClientes= DAO.ClientesDao.loadBD();
            
            this.LblTotalClientes.setText("Hay "+ (this.dtClientes.getRowsLenth()) +" Clientes");
            
            this.siguiente();
        } catch (Exception ex) {
            Logger.getLogger(ClientesAll.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
    }
    
     private void cargarBD(int pos){
        
        try {
            linea=pos;
            dtClientes= DAO.ClientesDao.loadBD();
            if(dtClientes.getRowsLenth()>linea){
            this.LblTotalClientes.setText("Hay "+ (this.dtClientes.getRowsLenth()) +" Clientes");
            
            this.siguiente();
            }
        } catch (Exception ex) {
            Logger.getLogger(ClientesAll.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClientesAll dialog = new ClientesAll(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnSiguiente;
    private javax.swing.JLabel LblTotalClientes;
    private javax.swing.JTextField TxtDNI;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtIDCliente;
    private javax.swing.JTextArea TxtInfo;
    private javax.swing.JTextField TxtMovil;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtNumCarpeta;
    private javax.swing.JTextField TxtTelf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
